---
- name: Add a repo
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: http://dl-cdn.alpinelinux.org/alpine/v3.16/community
    create: yes

- name: Update repositories and install curl package
  community.general.apk:
    name: curl, tar, python3, py3-pip
    update_cache: true

- name: Install python packages
  ansible.builtin.pip:
    name: pyyaml

#- name: Recursively remove everything in /tmp/
#  ansible.builtin.file:
#    path: /tmp/*
#    state: absent