---
- name: Remove SSH IPs from known_hosts
  known_hosts:
    path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
    name: "{{ item }}"
    state: absent
  loop: "{{ groups['all'] }}"
  when: hostvars[item].ansible_host is defined

- name: Save SSH fingerprints
  shell: ssh-keyscan -H {{ hostvars[item].ansible_host }} >> "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
  loop: "{{ groups['all'] }}"
  when: hostvars[item].ansible_host is defined
  
- name: Add a repo
  ansible.builtin.lineinfile:
    path: /etc/apk/repositories
    line: http://dl-cdn.alpinelinux.org/alpine/v3.16/community
    create: yes
  when: ansible_distribution == 'Alpine'

- name: Update repositories and install curl package
  community.general.apk:
    name: curl, tar, python3, py3-pip
    update_cache: true
  when: ansible_distribution == 'Alpine'

- name: Install python packages
  pip:
    name:
      - pyyaml
      - kubernetes 
      - jmespath
  when: ansible_distribution == 'Alpine'