---
- hosts: all
  roles:
    - role: prep

- hosts: master
  roles:
    - role: k3s/01Build

#- hosts: all
#  roles:
#    - role: k3s/03Helm

#- hosts: Hauptmann
#  roles:
#    - role: k3s/04Longhorn
#    - role: k3s/05Bind9
#    #- role: k3s/database
#    - role: k3s/apache
#    - role: k3s/zz_Traefik