apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-bind9
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/root/configfiles/"