apiVersion: v1
kind: Service
metadata:
  name: bind9
  labels: 
    app: bind9
spec:
  type: ClusterIP
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  externalIPs:
    - 49.13.5.181
    - 128.140.50.61
  selector:
     app: bind9