apiVersion: v1
kind: Service
metadata:
  name: bind9
  labels: 
    app: bind9
spec:
  type: ClusterIP
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  externalIPs:
    - 116.202.8.94
    - 95.217.156.114