---

#######
## Pass auf das ist alles für
## x86 und nicht ARM
####
- name: download helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.10.3-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Creates directory .kube
  file:
    path: /root/.kube/
    state: directory

- name: Copy K3s for kubectl
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /root/.kube/config
    remote_src: true
    mode: '0600'

- name: copy helm into /usr/local/bin/helm
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: true
    mode: '0744'


### HELM REPOS FOR FURTHER TASKS

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: longhorn 
    repo_url: "https://charts.longhorn.io"

- name: Add helm repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"
    
### HIER FEHLT helm repo update