---
- name: Update repositories and install curl package
  community.general.apk:
    name: docker, docker-compose
    update_cache: true

- name: Make "docker" start on boot and start now, if not started.
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started