---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      repository: https://charts.longhorn.io
      version: latest
  values: