apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  chart:
    spec:
      chart: longhorn
      version: latest
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
  interval: 5m
  values:
    namespace:
      - longhorn