apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: default
spec:
  interval: 5m
  chart:
    repository: https://charts.longhorn.io
    name: longhorn
    version: latest
  values:
