---
- name: Add helm repo
  kubernetes.core.helm_repository:
    name: longhorn 
    repo_url: "https://charts.longhorn.io"

### HIER FEHLT helm repo update

- name: Deploy longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    release_namespace: longhorn-system
    create_namespace: true