---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  externalIPs:
  - 49.13.5.181
  ports:
  - port: 9080
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx